// <auto-generated />
namespace RealPollSignalR.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class _201403031941252_Id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201403031941252_Id));
        
        string IMigrationMetadata.Id
        {
            get { return "201403032151170_201403031941252_Id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
